package com.example.myapplication

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Auto-generated string constants data class
 * Generated from Google Sheets
 * Sheet ID: 1x7XMEJYv6jVppuA3fV-Srp5OmyrCgdl8w1m0ETsxzxw
 * Total unique keys: 12
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run the Python generator script to update
 */
@JsonClass(generateAdapter = true)
data class StringApp(
    @Json(name = "profile_name") val profileName: String = "profile_name",
    @Json(name = "profile_bio") val profileBio: String = "profile_bio",
    @Json(name = "change_lang") val changeLang: String = "change_lang",
    @Json(name = "posts") val posts: String = "posts",
    @Json(name = "followers") val followers: String = "followers",
    @Json(name = "following") val following: String = "following",
    @Json(name = "edit_profile") val editProfile: String = "edit_profile",
    @Json(name = "male") val male: String = "male",
    @Json(name = "joined") val joined: String = "joined",
    @Json(name = "email") val email: String = "email",
    @Json(name = "phone_number") val phoneNumber: String = "phone_number",
    @Json(name = "birth_date") val birthDate: String = "birth_date"
)

// Property mapping for reference:
// Original Key -> Kotlin Property
// "profile_name" -> profileName
// "profile_bio" -> profileBio
// "change_lang" -> changeLang
// "posts" -> posts
// "followers" -> followers
// "following" -> following
// "edit_profile" -> editProfile
// "male" -> male
// "joined" -> joined
// "email" -> email
// "phone_number" -> phoneNumber
// "birth_date" -> birthDate